spring:
  data.redis.repositories.enabled: true
  #redis.host: 127.0.0.1
  redis.host: 192.168.0.12
  redis.ssl: false
  redis.port: 6379

#spring.redis.pool.max-active=10
#spring.redis.pool.max-idle=10
# spring.redis.pool.max-wait=30000